extra:
  search:
    language: 'en, pt'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

nav:
- Introdução: index.md

plugins:
  - search

site_name: Programação Orientada a Objetos
site_description: Disciplina de Programação Orientada a Objetos
site_author: Allainclair Flausino dos Santos
site_url: https://allainclair.github.io/disc-estrutura-dados

theme:
  language: pt
  name: material
